### ISSUE TITLE
Implement Calendar Feature for Event Tracking

### ISSUE THREAD

**Issue by johnnyBettencourt** [johnnyBettencourt/family-life-tracker#3]
**Description**:
The family life tracker app currently has a tasks feature, and the next step is to implement a calendar feature. This feature will be an integral part of the dashboard, allowing users to add, view, and track family events. The calendar will be accessible from a dedicated tab and should integrate seamlessly with the overall design and functionality of the app.

**Goals**:
- Implement a calendar feature using `react-big-calendar` and `date-fns`.
- Enable users to add, view, and manage events.
- Ensure it aligns with the app's aesthetic.
- Ensure smooth interaction between the calendar and other features, like tasks.

**Technical Considerations**:
- Utilize `react-redux` with RTK for state management.
- Ensure that the calendar is responsive and user-friendly.
- Consider the use of `date-fns` for date handling and manipulations.
- Explore the functionalities offered by `react-big-calendar` to determine the best user experience.

**User Stories**:
1. As a user, I want to view my entire day at a glance on the dashboard, including calendar events.
2. As a user, I want to add new events to the calendar with details such as title, date, and time.
3. As a user, I want to edit or delete existing events on the calendar.
4. As a user, I want the calendar to be visually consistent with the rest of the app.

**Additional Notes**:
- This feature should be developed in a dedicated branch (e.g., `feature/calendar`).

**Comment by sheikahamed123** [comment]
I'll contribute
